filter:
    excluded_paths:
        - "Tests/"
tools:
    external_code_coverage:
        timeout: 900


build:
    dependencies:
        override:
            - true
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
